# Generated by Django 3.1.5 on 2021-01-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postblog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='postblog',
            name='tags',
        ),
        migrations.DeleteModel(
            name='CategoryBlog',
        ),
        migrations.DeleteModel(
            name='PostBlog',
        ),
        migrations.DeleteModel(
            name='TagBlog',
        ),
    ]
